RUNNING:
  LOG_LEVEL: DEBUG

VECTOR_DB:
  URL: http://chromadb:8000
  COLLECTION_NAME: "test"
  EMBEDDER_NAME: "all-MiniLM-L6-v2"

ASR:
  TRANSCRIPTION_URL: http://asr:8000/transcribe
  LANGUAGES_URL: http://asr:8000/languages
  WHISPER_MODEL_NAME: "small" # "large-v3-turbo"
#tiny, tiny.en, base, base.en, small, small.en, distil-small.en, medium, medium.en,
#distil-medium.en, large-v1, large-v2, large-v3, large, distil-large-v2,
#distil-large-v3

LLM:
  URL: http://ollama:11434
  TEMPERATURE: 0.0
  MODEL_NAME: "gemma2:2b"
  TOP_K: 1 # A higher value (e.g. 100) will give more diverse answers, while a lower value (e.g. 10) will be more conservative. (Default: 40)
  TOP_P: 0.1 # A higher value (e.g., 0.95) will lead more diverse text, while a lower value (e.g., 0.5) will generate more focused and conservative text. (Default: 0.9)
  # OLLAMA: "mistral:instruct"
  # MODEL_NAME: "mistral-7b-instruct-v0.3"  
  # HUGGINGFACE_TOKEN: "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"

RAG:
  # WEBHOOK_AGENT_REACT_URL: http://rag:8000/react_agent_result
  WEBHOOK_RAG_URL: http://rag:8000/rag_result
  # REACT_AGENT_PROMPT: "/app/src/prompts/agent_react_v2.txt"
  RAG_PROMPT: "/app/src/prompts/rag_basic_v2.txt"
  # RAG_EXTRACT_HEADING_PROMPT: "/app/src/prompts/extract_heading.txt"
  OUTPUT_NO_CONTEXT_ANSWER: "No relevant information found in the documents."
  OUTPUT_NOT_MATCH_ANSWER_CONTEXT : "The question does not match with the context provided."
  NUM_DOCUMENTS: 3
  # SEARCH_KWARGS:
  #   score_threshold: 0.8 # Umbral mínimo de relevancia, si es mas bajo mas similar es
    # fetch_k: 20 # Cantidad de documentos que se deben pasar al algoritmo mmr
    # lambda_mult: 0.5 # Diversidad de resultados obtenidos por MMR;1 para diversidad mínima y 0 para máxima. (Valor predeterminado: 0,5)
    # where_document: {"$contains": heading} # Filtrar por metadatos del documento
    # filter: {"headings": {"$in": heading}}

TTS:
  URL: http://tts:8000
  MODEL_NAME: tts_models/en/vctk/vits
  DEFAULT_SPEAKER: p225          # Deja vacío si el modelo no es multi-speaker
  SAMPLE_RATE: 22050
  WARMUP_TEXT: "System warmup completed."
  MAX_TEXT_LENGTH: 500
  RETURN_BASE64: true

# Timeouts (segundos) para las llamadas HTTP desde Streamlit
TIMEOUTS:
  ASR: 100         # Tiempo máximo para transcribir audio
  RAG: 100          # Tiempo máximo para la respuesta del servicio RAG
  AGENT_REACT: 100  # Tiempo máximo para la respuesta del Agent React